balena-io-modules/device-diagnostics

scripts/checks.sh

container-engine: properly check for aliveness of engine

---

scripts/checks.sh

Connects-to: #147
Connects-to: #112

balenaOS: warn about a custom device type (custom OS)

---

diagnostics.md
scripts/checks.sh

checks: add temperature > 80C check

---

scripts/diagnose.sh

dmesg: add full timestamps to output

---

diagnostics.md
scripts/checks.sh

OS: add check for any failed boot/rollback breadcrumbs

---

scripts/checks.sh
scripts/diagnose.sh

supervisor: use LISTEN_PORT as sourced from config.json

---

scripts/diagnose.sh

openvpn: properly collect logs from journald

---

scripts/diagnose.sh

OS: list failed units in diagnostics

---

scripts/checks.sh

supervisor: time out engine call

---

.github/CODEOWNERS

meta: add wrboyce as CODEOWNER

---

diagnostics.md
scripts/checks.sh

checks: add catchall networking check

---

.resinci.yml

CI: disable node testing

---

scripts/checks.sh

checks: ensure every call to ENG is timed out

---

diagnostics.md

docs: add Depends on section, mention some inter-check dependencies

---

scripts/checks.sh

networking: make test_wifi play nicer with multiple configured ints

---

scripts/checks.sh

meta: add note about source of 60

---

scripts/checks.sh

Connects-to: #125
Connects-to: #168

checks: add white/blacklisting for device-specific checks

---

diagnostics.md
scripts/checks.sh

checks: confirm root media has fully expanded

---

scripts/checks.sh

os-rollbacks: properly detect either type of rollback

---

diagnostics.md
scripts/checks.sh

checks: remove legacy check_dns in favor of revamped networking check

---

scripts/checks.sh

service-restarts: properly count + track timed out service inspections

---

scripts/checks.sh

check_localdisk: add back mistakenly dropped expansion test

---

diagnostics.md
scripts/checks.sh

checks: confirm running supervisor is a released edition and matches API

---

scripts/checks.sh

checks: fix up math comparison

---

diagnostics.md
scripts/checks.sh

Connects-to: https://github.com/balena-io/device-diagnostics/issues/157

checks: add support for user service health checking

---

diagnostics.md
scripts/checks.sh

checks: prefix user service checks appropriately

---

scripts/checks.sh
scripts/diagnose.sh

networking: reuse root CA for permitted MiTM

---

.github/CODEOWNERS

meta: add saintaardvark as CODEOWNER

---

scripts/checks.sh

typo: do a proper comparison not an assignment

---

scripts/checks.sh

checks: clean up rollback notifications

---

scripts/checks.sh
scripts/diagnose.sh

TLS: expand allowed bundles to include all available device bundles

---

scripts/checks.sh

checks: filter null service healthchecks from results

---

diagnostics.md

docs: update check_image_corruption docs to mention timeouts

---

diagnostics.md

docs: clarify the nuance surrounding write latency calculations

---

scripts/checks.sh

Connects-to: https://github.com/balena-io/device-diagnostics/issues/200

localdisk: select the correct boot media

---

scripts/diagnose.sh

balena-engine: add extra debug stacktrace for balena-engine

---

diagnostics.md

docs: fix up markdown formatting

---

.github/CODEOWNERS

codeowners: remove zubairlk

---

scripts/checks.sh

meta: fix up inconsistent indentation

---

scripts/diagnose.sh

diagnostics: add chronyd logs to output

---

scripts/checks.sh

check_balenaOS: handle case of multiple upstream hostapps

---

scripts/checks.sh

check_temperature: clean up current temp check to read from multiple sensors

---

scripts/diagnose.sh

diagnostics: start grabbing modem data

---

scripts/diagnose.sh

diagnostics: add extlinux support

---

scripts/diagnose.sh

time: get chrony's source information

---

scripts/checks.sh

[Apologies if you saw a half-done PR before...I obviously fat-fingered something, and had to come back and redo the edits I was trying the first time.]
This checks if balena engine is refusing connections.   Specifically:
- It also refactors `check_container_engine()` to be a "bag-of-holding" for engine tests, the way we do with `check_networking()` and `check_localdisk()`.
- It adds a new check for engine responsiveness using the cli (`balena ps`)
```
{
"name": "check_container_engine",
"success": true,
"status": "No container_engine issues detected"
`
}
```
I followed this procedure to cause problems with log messages matching #226:
```
root@f41b2eb:~# ls -l /var/run/*sock
srw-rw---- 1 root balena-engine 0 Jul  8 20:30 /var/run/balena-engine.sock
srw-rw---- 1 root balena-engine 0 May 26 …
```

Add check to see if container engine responding to commands

---

scripts/diagnose.sh

hup: start grabbing more HUP logs for future debugging

---

scripts/checks.sh

check_balenaos: report the custom device type slug upon failure

---

scripts/diagnose.sh

ref. https://www.flowdock.com/app/rulemotion/r-product/threads/gIr9O4P2AW5lBCaxAaJvdPPB187

supervisor: grab all supervisor lock dirs in diagnostics

---

scripts/diagnose.sh

diagnostics: grab half a year of HUP logs

---

scripts/diagnose.sh

diagnostics: grab error from journal

---

.github/CODEOWNERS

meta: update codeowners

---

scripts/checks.sh

Connects-to: https://github.com/balena-io/balena-api/pull/2786

supervisor: stop checking for remote/local mismatch

---

scripts/checks.sh

stick to consistent tabbing

---

scripts/checks.sh

networking: dockerhub access is no longer a requirement

---

scripts/diagnose.sh

Connects-to: https://github.com/balena-io/device-diagnostics/issues/262

diagnose: grab any logs from ModemManager

---

scripts/checks.sh
scripts/diagnose.sh

device-type: grab device-type.json, drop custom OS detection

---

scripts/checks.sh

... but ignore the PMIC-Die zone, because the actual
temperature cannot be read and the driver reports
a constant value of 100C.
Change-type: Patch
Signed-off-by: Alexandru Costache <alexandru@balena.io>
Fixes https://github.com/balena-os/balena-jetson/issues/142

checks: Allow temperature checks to run on Jetson devices

---

scripts/checks.sh

This is a newly supported device, let's add it to our
list for temperature checking.
Signed-off-by: Alexandru Costache <alexandru@balena.io>

checks: Add Floyd Nano device type to temperature whitelist

---

diagnostics.md
scripts/checks.sh

throttling: drop vcgencmd-dependent check

---

scripts/checks.sh

supervisor: use output to confirm supervisor is up & running

---

scripts/diagnose.sh

Useful to debug network config errors

add docker network information

---

diagnostics.md
scripts/checks.sh

Signed-off-by: Chris Crocker-White <chriscw@balena.io>

Rename applications to fleets as appropriate

---

scripts/checks.sh

Resolves: https://github.com/balena-io-modules/device-diagnostics/issues/288

Deprecate references to VARIANT from os-config

---

diagnostics.md

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

patch: Add dashboard diagnostics screenshot

---

diagnostics.md

- patch: Add dashboard diagnostics screenshot
- patch: diagnostics

Improve wording of diagnostics run

---

diagnostics.md
scripts/checks.sh

Resolves: https://github.com/balena-io-modules/device-diagnostics/issues/298

Update DNS check docs to indicate only failed tests are shown 

---

diagnostics.md
scripts/checks.sh

Resolves: https://github.com/balena-io-modules/device-diagnostics/issues/297

Combine user service checks and container restart checks

---

scripts/checks.sh

See: https://github.com/balena-io-modules/device-diagnostics/pull/302

checks.sh: Add missing parenthesis in check_balenaOS

---

scripts/checks.sh

checks: update undervoltage grep pattern to match in newer kernels

---

diagnostics.md

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

patch: Fix diagnostics spelling/headings

---

diagnostics.md

patch: Revert to linking with docs path than GitHub URLs

---

diagnostics.md

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

patch: Document a way to surface healthchecks to dashboard

---

diagnostics.md

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

Convert device health checks data to tables

---

scripts/checks.sh

See: https://balena.fibery.io/Work/Project/Use-the-release-semver-fields-along-with-release_tags-across-all-our-components-404
See: https://balena.fibery.io/Work/Task/Change-the-device-Diagnostics-to-use-the-release-semver-fields-1868

check_balenaOS: Support detecting releases w/o release_tags

---

scripts/checks.sh

Update current raspberry-pi based boards slugs
Change-type:patch

checks: Update current RPI boards list
