balena-io-modules/device-diagnostics

.github/CODEOWNERS
=> meta: update codeowners to include gareth for docs

scripts/diagnose.sh
diagnose: add engine journal specifically (omitting user apps)
standardize journalctl calls
get all warning prio messages in journal
=> improve journalctl interactions

diagnostics.md
Signed-off-by: Hugh Brown <hugh@balena.io>
While going through the Advanced CLI masterclass, I had a device that failed the `check_image_corruption` diagnostic.  When displayed in the dashboard (staging, for the record), the link to further information (https://www.balena.io/docs/reference/diagnostics/#check_image_corruption) did not work.  This PR is meant to address that.
I've tried to create a good summary of the problem, but suggestions are most welcome.  In particular, I'm unsure about the link to `balena-engine image prune`: I'm not certain if we generally give customers commands to run on the device, and I don't know if we have a better/prettier page to link to for `balena-engine` commands (as we do for [balena-cli](https://www.balena.io/docs/reference/balena-cli/ …
=> Add documentation for check_image_corruption to diagnostics.md

.github/CODEOWNERS
=> remove gareth as codeowner of markdown

scripts/checks.sh
This is the same logic used in resinhup to perform delta updates: https://github.com/balena-os/resinhup/blob/master/upgrade-2.x.sh#L721-L730
Connects-to: https://github.com/balena-io/device-diagnostics/issues/156
=> check_balenaOS: adjust query to reflect public apps (ESR support)

diagnostics.md, scripts/checks.sh
This check in its current form has a number of disadvantages:
- It causes a lot of IO.  Under the hood, balena-engine is:
- reading the individual layers;
- writing them out to /var/lib/docker/tmp;
- then reading them all back in, so it can write to stdout.
- One consequence is that the `docker save` command can take longer than the current 10s timeout (particularly if there are a lot of images, or if the images are large), despite the device and its storage being perfectly healthy.
- While it is good to know if an image has corruption, it's probably more important to know if the underlying storage is having problems; this check is not a great way of determining if that is happening.
Thus, for now we're better off without this check.  We can investigate other approaches to verifying …
=> Remove image corruption check, as it is currently too noisy

scripts/checks.sh
This adds a count of under-voltage events.  
Testing on my RPi4, happy case:
```
{
"name": "check_under_voltage",
"success": true,
"status": "No under-voltage events detected"
}
```
Sad case:
```
{
"name": "check_under_voltage",
"success": false,
"status": "2 under-voltage events detected, check/change the power supply ASAP"
}
```
Connects-to: #217
Signed-off-by: Hugh Brown <hugh@balena.io>
=> Include count of under-voltage events when reporting problems

diagnostics.md, scripts/checks.sh
This adds two checks that take different approaches to detecting CPU throttling:
- check_throttling_dmesg examines dmesg output for throttling events.  The original request at #183 was compared with [this page](https://access.redhat.com/solutions/134973);  
- check_throttling_vcgencmd examines the output of the Raspberry Pi utility `vcgencmd` to determine if throttling is currently happening, or has occurred in the past.
Testing, happy case:
```
[snip]
{
"name": "check_throttling_dmesg",
"success": true,
"status": "No cpu throttling events detected"
},
{
"name": "check_throttling_vcgencmd",
"success": true,
"status": "No Raspberry Pi throttling events detected"
},
```
Sad case, dmesg:
```
[snip]
{
"name": "check_throttling_dmesg",
"success": false,
"status": "2 cpu throttling events …
```
=> Detect CPU throttling events

scripts/diagnose.sh
written to during config: https://github.com/balena-os/meta-balena/blob/9ace976ea9d757d3d928ed59ce60c4118bb9d557/meta-balena-common/recipes-connectivity/networkmanager/resin-files/99dhcp_ntp#L3
=> timesync: check if DHCP passed in any local timeservers

scripts/diagnose.sh
The dashboard 'Standard error' display for 'Device Diagnostics' reports the following error:
'bash: line 27: timeout -v 1: command not found'
This issue is due to the double quotes used in the corresponding 'if' statement. Adding an additional redirect of stderr to this commands hides any error messages for the cases where the '-v' option is not supported by the version of 'timeout' being used.
This fix has been tested as a simple, isolated code snippet on the balenaOS (2.51.1+rev1) command line running on a RPi3.
Connects-to: #234
Signed-off-by: Mark Corbin <mark@balena.io>
=> Fix timeout 'command not found' error in diagnose.sh

diagnostics.md
This closes #208.
@xginn8: The NTP section (right before I add the masterclass link) says that the time can be set via HTTP headers.  Do you have an example command for this?  If not, I'll come up with something and add it here.
Signed-off-by: Hugh Brown <hugh@balena.io>
=> Add links to balena Masterclass documents where appropriate

scripts/checks.sh
when output is potentially user-controlled, interpret as ascii
Connects-to: https://github.com/balena-io/device-diagnostics/issues/246
=> do not interpret control characters when echoing into jq

scripts/checks.sh
This adds a check to verify that the `data` partition is mounted read-write.  `lsblk` doesn't examine the mounts of the filesystem to see if they're read-only, so I'm using the contents of `/proc/mount`; this seems like the easiest, most likely-to-stay-consistent way of determining all three cases (mounted rw, mounted ro, not mounted at all).  
Happy case:
```
rroot@1364988:/lib/systemd/system# mount | grep /mnt/data ; /tmp/checks.sh | jq '.checks[] | select (.name == "check_localdisk")'
/dev/mmcblk0p6 on /mnt/data type ext4 (rw,relatime)
{
"name": "check_localdisk",
"success": true,
"status": "No localdisk issues detected"
}
```
Sad case -- mounted read-only:
```
root@1364988:/lib/systemd/system# mount | grep /mnt/data ; /tmp/checks.sh | jq '.checks[] | select (.name == …
```
=> Check if the data partition is mounted read-write

scripts/diagnose.sh
This adds md5sum fingerprint checking to `diagnose.sh`.  To accommodate https://github.com/balena-os/meta-balena/issues/1618, we explicitly skip checking `/var/cache/ldconfig/aux-cache` in order to avoid crashing vulnerable systems.
Checked on my devenv.  Happy case:
```
--- grep -v /var/cache/ldconfig/aux-cache /resinos.fingerprint | md5sum --quiet -c - ---
2020-10-23 18:44:44.358042552+00:00
real	0m 7.82s
user	0m 1.93s
sys	0m 1.12s
```
Sad case (two files modified, one removed):
```
--- grep -v /var/cache/ldconfig/aux-cache /resinos.fingerprint | md5sum --quiet -c - ---
2020-10-23 18:47:11.946180068+00:00
/etc/sysctl.conf: FAILED
/usr/share/ModemManager/mm-dell-dw5821e-carrier-mapping.conf: FAILED
/usr/share/usb_modeswitch/new.lst: FAILED open or read
Command exited with non-zero status …
```
=> Add md5sum fingerprint checking to diagnostics

scripts/checks.sh, scripts/diagnose.sh
Replace all references to the 'resin-vars' script with 'balena-config-vars' as it has been renamed.
This PR needs to be merged when https://github.com/balena-os/meta-balena/pull/2142 has been merged.
Changelog-entry: device-diagnostics: replace references to resin-vars
Signed-off-by: Mark Corbin <mark@balena.io>
=> device-diagnostics: replace references to resin-vars

scripts/diagnose.sh
Some users have applications that are sensitive to boot performance, and
diagnostics can help trace the cause of regressions in boot time, or
misbehaving services.
Add `systemd-analyze` and `systemd-analyze critical-chain` to
diagnostics to get an overall boot time, as well as a breakdown by unit.
Signed-off-by: Joseph Kogut <joseph@balena.io>
Links to: https://github.com/balena-io-modules/device-diagnostics/issues/271
=> Add diagnostics for boot performance

scripts/checks.sh, scripts/diagnose.sh
Keep references to resin namespaces for now
=> Rename resin-supervisor to balena-supervisor

scripts/checks.sh
Avoid checking DNS servers that have since been
changed/removed by only parsing the logs of the running
dnsmasq instance.
Resolves: https://github.com/balena-io-modules/device-diagnostics/issues/280
=> checks: Filter dnsmasq servers by running instance

scripts/checks.sh
the upstream dns diagnostics check does not currently check for IPv6 addresses
=> Check for IPv6 addresses

scripts/checks.sh
skip first line and first 3 columns to avoid matching date instead of IPv6 addresses
In order to avoid matching dates when matching IPv6 addresses, I only matched the last field.
Unfortunately, dnsmasq doesn't always print the DNS as the last field per https://github.com/balena-io-modules/device-diagnostics/pull/286#issuecomment-918132277
Instead, simply skip the first line and the first 3 columns which contain the log date.
=> Check for IPv6 DNS's without matching dates

scripts/checks.sh
This checks if the device has a default gateway for an interface with ipv4 and ipv6 addresses and exits the ip stack checks if the device doesn't. 
closes #292
=> Improve ip stack checks

scripts/checks.sh, scripts/diagnose.sh
Add a check that triggers when we find a storage migration log file,
which will only exist after a failed migration.
And the equivalent line to the diagnose script to pull out the actual
logs when the file exists.
=> engine: add storage migration check

scripts/checks.sh
Before this PR, the `test_ipv6_stack` check was being effectively bypassed because the `ip -6 route get` command was always failing because of a typo in the IPv6 address, which was interpreted by the script as an unavailable IPv6 stack.
Connects-to: #292
Connects-to: #294
=> Fix IPv6 address (typo) used in the test_ipv6_stack check

scripts/diagnose.sh
Diagnostic executions are failing with
```
--- balena network inspect $(balena ps --quiet | tr "\n" " ") ---
Error: No such network: ef3a43ba55d4
Error: No such network: af338f332384
Error: No such network: 8eef54236371
```
We were passing container IDs to `balena network inspect`. This fixes the command to pass network IDs, as expected.
=> Fix Engine network diagnostic

versionist.conf.js
The `package.json` file was removed with the rest of the balenaCI leagacy code.
=> versionist: remove updating packages.json version
